/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)core_version_buildid.h    generated by: makeheader    Mon Apr 25 07:50:29 2016
 *
 *		built from:	buildid.ifc
 */

#ifndef core_version_buildid_h
#define core_version_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "NDDSCORE_VERSION_5.2.3.0_BUILD_2016-04-25T07:37:01-07:00_RTI_RELEASE"
#endif

#endif /* core_version_buildid_h */
