/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)routingservice_transformation.h    generated by: makeheader    Mon Apr 25 08:04:01 2016
 *
 *		built from:	transformation.ifc
 */

#ifndef routingservice_transformation_h
#define routingservice_transformation_h



  #include "routingservice/routingservice_infrastructure.h"
  
  #ifdef __cplusplus
      extern "C" {
  #endif


struct RTI_RoutingServiceTransformationPlugin;


typedef void * RTI_RoutingServiceTransformation;


typedef struct RTI_RoutingServiceTransformationPlugin * 
(*RTI_RoutingServiceTransformationPlugin_CreateFcn)(
    const struct RTI_RoutingServiceProperties * properties,
    RTI_RoutingServiceEnvironment * env);


typedef void (*RTI_RoutingServiceTransformationPlugin_DeleteFcn)(
    struct RTI_RoutingServiceTransformationPlugin * plugin,
    RTI_RoutingServiceEnvironment * env);

 
typedef RTI_RoutingServiceTransformation 
(*RTI_RoutingServiceTransformationPlugin_CreateTransformationFcn)(
    struct RTI_RoutingServiceTransformationPlugin * plugin,
    const struct RTI_RoutingServiceTypeInfo * input_type_info,
    const struct RTI_RoutingServiceTypeInfo * output_type_info,
    const struct RTI_RoutingServiceProperties * properties,
    RTI_RoutingServiceEnvironment * env);

 
typedef void (*RTI_RoutingServiceTransformationPlugin_DeleteTransformationFcn)(
    struct RTI_RoutingServiceTransformationPlugin * plugin,
    RTI_RoutingServiceTransformation transformation,
    RTI_RoutingServiceEnvironment * env);


typedef void (*RTI_RoutingServiceTransformation_TransformFcn)(
     RTI_RoutingServiceTransformation transformation,
     RTI_RoutingServiceSample ** out_sample_lst,
     RTI_RoutingServiceSampleInfo ** out_info_lst,
     int * out_count,
     RTI_RoutingServiceSample * in_sample_lst,
     RTI_RoutingServiceSampleInfo * in_info_lst,
     int in_count,
     RTI_RoutingServiceEnvironment * env);


typedef void (*RTI_RoutingServiceTransformation_ReturnLoanFcn)(
     RTI_RoutingServiceTransformation transformation,
     RTI_RoutingServiceSample * sample_lst,
     RTI_RoutingServiceSampleInfo * info_lst,
     int count,
     RTI_RoutingServiceEnvironment * env);

 
typedef void (*RTI_RoutingServiceTransformation_UpdateFcn)(
    RTI_RoutingServiceTransformation transformation,
    const struct RTI_RoutingServiceProperties * properties,
    RTI_RoutingServiceEnvironment * env);


struct RTI_RoutingServiceTransformationPlugin {
    int _init;
    struct RTI_RoutingServiceVersion _rs_version;

    /*e \brief The version of this transformation plugin */
    struct RTI_RoutingServiceVersion plugin_version;

    /*e \brief Handles the deletion of the transformation plugin. */
    RTI_RoutingServiceTransformationPlugin_DeleteFcn
        transformation_plugin_delete;
    /*e \brief Handles the creation of transformations. */
    RTI_RoutingServiceTransformationPlugin_CreateTransformationFcn
	transformation_plugin_create_transformation;
    /*e \brief Handles the deletion of transformations. */
    RTI_RoutingServiceTransformationPlugin_DeleteTransformationFcn
	transformation_plugin_delete_transformation;

    /*e \brief Handles the transformation of samples. */
    RTI_RoutingServiceTransformation_TransformFcn transformation_transform;
    /*e \brief Handles the return of the loan taken on the transformed samples. */
    RTI_RoutingServiceTransformation_ReturnLoanFcn transformation_return_loan;
    /*e \brief Handles the update of the transformation configuration. */
    RTI_RoutingServiceTransformation_UpdateFcn transformation_update;

    /*e @brief A place for transformation implementors to keep a pointer to data that 
        may be needed by the implementation. */
    void * user_object;
};



/*e \ingroup RTI_RoutingServiceTransformationModule
 \hideinitializer
 @brief Initializes the plugin structure.

 This macro must be called to initialize the
 return value of RTI_RoutingServiceTransformationPlugin_CreateFcn

 @param transf Pointer to the transformation plugin structure
 
 @see \ref RTI_RoutingServiceTransformationPlugin_CreateFcn
*/
#define RTI_RoutingServiceTransformationPlugin_initialize(transf)             \
{                                                                             \
    struct RTI_RoutingServiceVersion rsVersion = RTI_ROUTING_SERVICE_VERSION; \
    struct RTI_RoutingServiceVersion transfVersion = {0,0,0,0};               \
    (transf)->_init = 7654321;                                                \
    (transf)->_rs_version = rsVersion;                                        \
    (transf)->plugin_version = transfVersion;                                 \
    (transf)->transformation_plugin_delete = 0;                               \
    (transf)->transformation_plugin_create_transformation = 0;                \
    (transf)->transformation_plugin_delete_transformation = 0;                \
    (transf)->transformation_transform = 0;                                   \
    (transf)->transformation_return_loan = 0;                                 \
    (transf)->transformation_update = 0;                                      \
    (transf)->user_object = 0;                                                \
}



  #ifdef __cplusplus
    }	/* extern "C" */
  #endif

#endif /* routingservice_transformation_h */
