/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)rti_dl_dll_cpp.h    generated by: makeheader    Mon Apr 25 07:52:11 2016
 *
 *		built from:	dll_cpp.ifc
 */

#ifndef rti_dl_dll_cpp_h
#define rti_dl_dll_cpp_h



#if defined(RTI_WIN32) || defined(RTI_WINCE)
  #if defined(RTI_rti_dl_cpp_DLL_EXPORT)
    #define RTIDLCPPDllExport __declspec( dllexport )
  #else
    #define RTIDLCPPDllExport
  #endif /* RTI_rti_dl_cpp_DLL_EXPORT */

  #if defined(RTI_rti_dl_cpp_DLL_VARIABLE) 
    #if defined(RTI_rti_dl_cpp_DLL_EXPORT)
      #define RTIDLCPPDllVariable __declspec( dllexport )
    #else
      #define RTIDLCPPDllVariable __declspec( dllimport )
    #endif /* RTI_rti_dl_cpp_DLL_EXPORT */
  #else 
    #define RTIDLCPPDllVariable
  #endif /* RTI_rti_dl_cpp_DLL_EXPORT */
#else
  #define RTIDLCPPDllExport
  #define RTIDLCPPDllVariable
#endif /* RTI_WIN32 || RTI_WINCE */


#endif /* rti_dl_dll_cpp_h */
