#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'demo-nodes-py==0.0.0','console_scripts','listener_qos'
__requires__ = 'demo-nodes-py==0.0.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('demo-nodes-py==0.0.0', 'console_scripts', 'listener_qos')()
    )
