/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)ndds_version.h    generated by: makeheader    Mon Apr 25 07:51:01 2016
 *
 *		built from:	ndds_version.ifc
 */

#ifndef ndds_version_h
#define ndds_version_h


#define RTI_DDS_VERSION_MAJOR  5
#define RTI_DDS_VERSION_MINOR  2
#define RTI_DDS_VERSION_RELEASE 3
#define RTI_DDS_VERSION_REVISION 0

#endif /* ndds_version_h */
