/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_cpp_sequence_TSeq.h    generated by: makeheader    Mon Apr 25 07:51:14 2016
 *
 *		built from:	TSeq.cxx
 */

#ifndef dds_cpp_sequence_TSeq_h
#define dds_cpp_sequence_TSeq_h

#endif /* dds_cpp_sequence_TSeq_h */
