/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_cpp_data_TDataReader.h    generated by: makeheader    Mon Apr 25 07:51:15 2016
 *
 *		built from:	TDataReader.cxx
 */

#ifndef dds_cpp_data_TDataReader_h
#define dds_cpp_data_TDataReader_h

#endif /* dds_cpp_data_TDataReader_h */
