#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'examples-rclpy-minimal-publisher==0.0.0','console_scripts','publisher_local_function'
__requires__ = 'examples-rclpy-minimal-publisher==0.0.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('examples-rclpy-minimal-publisher==0.0.0', 'console_scripts', 'publisher_local_function')()
    )
