#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'teleop-twist-keyboard==0.6.0','console_scripts','teleop_twist_keyboard'
__requires__ = 'teleop-twist-keyboard==0.6.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('teleop-twist-keyboard==0.6.0', 'console_scripts', 'teleop_twist_keyboard')()
    )
