#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'examples-rclpy-minimal-subscriber==0.0.0','console_scripts','subscriber_lambda'
__requires__ = 'examples-rclpy-minimal-subscriber==0.0.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('examples-rclpy-minimal-subscriber==0.0.0', 'console_scripts', 'subscriber_lambda')()
    )
