/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)commend_srReaderService_impl.h    generated by: makeheader    Mon Apr 25 07:50:08 2016
 *
 *		built from:	srReaderService_impl.ifc
 */

#ifndef commend_srReaderService_impl_h
#define commend_srReaderService_impl_h


#ifdef __cplusplus
    extern "C" {
#endif



#define COMMEND_SR_READER_SERVICE_RECORD_EXCLUSIVE_AREA_LEVEL (4)
#define COMMEND_SR_READER_SERVICE_TABLE_EXCLUSIVE_AREA_LEVEL (2)



#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* commend_srReaderService_impl_h */
