/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_c_printformat.h    generated by: makeheader    Mon Apr 25 07:51:01 2016
 *
 *		built from:	printformat.ifc
 */

#ifndef dds_c_printformat_h
#define dds_c_printformat_h


#ifndef dds_c_xml_h
  #include "dds_c/dds_c_xml.h"
#endif

#ifdef __cplusplus
  extern "C" {
#endif


struct DDS_PrintFormat;


typedef void (*DDS_PrintFormat_printTopLevelBeginningFnc)(
        struct DDS_PrintFormat *self,
        struct RTIXMLSaveContext *dst,
        const char *name,
        int indent);


typedef void (*DDS_PrintFormat_printTopLevelEndingFnc)(
        struct DDS_PrintFormat *self,
        struct RTIXMLSaveContext *dst,
        const char *name,
        int indent);


typedef void (*DDS_PrintFormat_printComplexTypeBeginningFnc)(
        struct DDS_PrintFormat *self,
        struct RTIXMLSaveContext *dst,
        const char *name,
        int indent);


typedef void (*DDS_PrintFormat_printComplexTypeEndingFnc)(
        struct DDS_PrintFormat *self,
        struct RTIXMLSaveContext *dst,
        const char *name,
        int indent);


typedef void (*DDS_PrintFormat_printPrimitiveTypeBeginningFnc)(
        struct DDS_PrintFormat *self,
        struct RTIXMLSaveContext *dst,
        const char *name,
        int indent);


typedef void (*DDS_PrintFormat_printPrimitiveTypeEndingFnc)(
        struct DDS_PrintFormat *self,
        struct RTIXMLSaveContext *dst,
        const char *name,
        int indent);


typedef void (*DDS_PrintFormat_printArrayBeginningFnc)(
        struct DDS_PrintFormat *self,
        struct RTIXMLSaveContext *dst,
        const char *name,
        int indent);


typedef void (*DDS_PrintFormat_printArrayEndingFnc)(
        struct DDS_PrintFormat *self,
        struct RTIXMLSaveContext *dst,
        const char *name,
        int indent);


typedef void (*DDS_PrintFormat_printComplexItemBeginningFnc)(
        struct DDS_PrintFormat *self,
        struct RTIXMLSaveContext *dst,
        DDS_UnsignedLong member_index,
        int indent);


typedef void (*DDS_PrintFormat_printComplexItemEndingFnc)(
        struct DDS_PrintFormat *self,
        struct RTIXMLSaveContext *dst,
        DDS_UnsignedLong member_index,
        int indent);


typedef void (*DDS_PrintFormat_printPrimitiveItemBeginningFnc)(
        struct DDS_PrintFormat *self,
        struct RTIXMLSaveContext *dst,
        DDS_UnsignedLong member_index,
        int indent);


typedef void (*DDS_PrintFormat_printPrimitiveItemEndingFnc)(
        struct DDS_PrintFormat *self,
        struct RTIXMLSaveContext *dst,
        DDS_UnsignedLong member_index,
        int indent);


typedef void (*DDS_PrintFormat_printArrayItemBeginningFnc)(
        struct DDS_PrintFormat *self,
        struct RTIXMLSaveContext *dst,
        DDS_UnsignedLong member_index,
        int indent);


typedef void (*DDS_PrintFormat_printArrayItemEndingFnc)(
        struct DDS_PrintFormat *self,
        struct RTIXMLSaveContext *dst,
        DDS_UnsignedLong member_index,
        int indent);


typedef void (*DDS_PrintFormat_printUnionDiscriminatorBeginningFnc)(
        struct DDS_PrintFormat *self,
        struct RTIXMLSaveContext *dst,
        int indent);


typedef void (*DDS_PrintFormat_printUnionDiscriminatorEndingFnc)(
        struct DDS_PrintFormat *self,
        struct RTIXMLSaveContext *dst,
        int indent);


typedef void (*DDS_PrintFormat_printIndentFnc)(
        struct DDS_PrintFormat *self,
        struct RTIXMLSaveContext *dst,
        int count);


typedef void (*DDS_PrintFormat_printUnsetOptionalMemberBeginningFnc)(
        struct DDS_PrintFormat *self,
        struct RTIXMLSaveContext *dst,
        const char *name,
        int indent);


typedef void (*DDS_PrintFormat_printUnsetOptionalMemberEndingFnc)(
        struct DDS_PrintFormat *self,
        struct RTIXMLSaveContext *dst,
        const char *name,
        int indent);


struct DDS_PrintFormat {
    DDS_PrintFormat_printTopLevelBeginningFnc
        print_top_level_beginning;

    DDS_PrintFormat_printTopLevelEndingFnc
        print_top_level_ending;

    DDS_PrintFormat_printComplexTypeBeginningFnc
        print_complex_type_beginning;

    DDS_PrintFormat_printComplexTypeEndingFnc
        print_complex_type_ending;

    DDS_PrintFormat_printPrimitiveTypeBeginningFnc
        print_primitive_type_beginning;

    DDS_PrintFormat_printPrimitiveTypeEndingFnc
        print_primitive_type_ending;

    DDS_PrintFormat_printArrayBeginningFnc
        print_array_beginning;

    DDS_PrintFormat_printArrayEndingFnc
        print_array_ending;

    DDS_PrintFormat_printComplexItemBeginningFnc
        print_complex_item_beginning;

    DDS_PrintFormat_printComplexItemEndingFnc
        print_complex_item_ending;

    DDS_PrintFormat_printPrimitiveItemBeginningFnc
        print_primitive_item_beginning;

    DDS_PrintFormat_printPrimitiveItemEndingFnc
        print_primitive_item_ending;

    DDS_PrintFormat_printArrayItemBeginningFnc
        print_array_item_beginning;

    DDS_PrintFormat_printArrayItemEndingFnc
        print_array_item_ending;

    DDS_PrintFormat_printUnionDiscriminatorBeginningFnc
        print_union_discriminator_beginning;

    DDS_PrintFormat_printUnionDiscriminatorEndingFnc
        print_union_discriminator_ending;

    DDS_PrintFormat_printUnsetOptionalMemberBeginningFnc
        print_unset_optional_member_beginning;

    DDS_PrintFormat_printUnsetOptionalMemberEndingFnc
        print_unset_optional_member_ending;

    DDS_PrintFormat_printIndentFnc
        print_indent;

    const char *hexadecimal_opening_delimiter;

    const char *hexadecimal_closing_delimiter;

    const char *character_opening_delimiter;

    const char *character_closing_delimiter;

    const char *string_opening_delimiter;

    const char *string_closing_delimiter;

    const char *enum_opening_delimiter;

    const char *enum_closing_delimiter;

    const char *null_representation;

    const char *element_separator;

    const char *newline_representation;

    const char *indent_representation;

    int indent_factor;

    int initial_indent;

    DDS_Boolean enable_top_level_type_printing;

    DDS_Boolean enable_union_discriminator_printing;

    DDS_Boolean enable_enum_as_string_printing;
};


#define DDS_PrintFormat_INITIALIZER \
    {(DDS_PrintFormat_printTopLevelBeginningFnc)NULL, \
    (DDS_PrintFormat_printTopLevelEndingFnc)NULL, \
    (DDS_PrintFormat_printComplexTypeBeginningFnc)NULL, \
    (DDS_PrintFormat_printComplexTypeEndingFnc)NULL, \
    (DDS_PrintFormat_printPrimitiveTypeBeginningFnc)NULL, \
    (DDS_PrintFormat_printPrimitiveTypeEndingFnc)NULL, \
    (DDS_PrintFormat_printArrayBeginningFnc)NULL, \
    (DDS_PrintFormat_printArrayEndingFnc)NULL, \
    (DDS_PrintFormat_printComplexItemBeginningFnc)NULL, \
    (DDS_PrintFormat_printComplexItemEndingFnc)NULL,\
    (DDS_PrintFormat_printPrimitiveItemBeginningFnc)NULL, \
    (DDS_PrintFormat_printPrimitiveItemEndingFnc)NULL,\
    (DDS_PrintFormat_printArrayItemBeginningFnc)NULL, \
    (DDS_PrintFormat_printArrayItemEndingFnc)NULL,\
    (DDS_PrintFormat_printUnionDiscriminatorBeginningFnc)NULL, \
    (DDS_PrintFormat_printUnionDiscriminatorEndingFnc)NULL, \
    (DDS_PrintFormat_printUnsetOptionalMemberBeginningFnc)NULL, \
    (DDS_PrintFormat_printUnsetOptionalMemberEndingFnc)NULL, \
    (DDS_PrintFormat_printIndentFnc)NULL, \
    NULL,\
    NULL,\
    NULL,\
    NULL,\
    NULL,\
    NULL,\
    NULL,\
    NULL,\
    NULL,\
    NULL,\
    NULL,\
    NULL,\
    3,\
    0,\
    DDS_BOOLEAN_FALSE,\
    DDS_BOOLEAN_TRUE,\
    DDS_BOOLEAN_TRUE}

typedef enum {
    DDS_PRINT_FORMAT_DEFAULT     = 0,
    DDS_PRINT_FORMAT_XML         = 1,
    DDS_PRINT_FORMAT_JSON        = 2
} DDS_PrintFormatKind;

extern DDSCDllExport
DDS_ReturnCode_t DDS_PrintFormat_initialize(
        struct DDS_PrintFormat *self,
        DDS_PrintFormatKind formatKind);

extern DDSCDllExport
DDS_ReturnCode_t DDS_PrintFormat_finalize(
        struct DDS_PrintFormat *self,
        DDS_PrintFormatKind formatKind);

extern DDSCDllExport
struct DDS_PrintFormat * DDS_PrintFormat_new(
        DDS_PrintFormatKind formatKind);

extern DDSCDllExport
void DDS_PrintFormat_delete(
        struct DDS_PrintFormat *self,
        DDS_PrintFormatKind formatKind);

extern DDSCDllExport
DDS_Boolean DDS_PrintFormat_is_valid(
        struct DDS_PrintFormat *self);


#ifdef __cplusplus
    }   /* extern "C" */
#endif

#endif /* dds_c_printformat_h */
