/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_c_buildid.h    generated by: makeheader    Mon Apr 25 07:51:01 2016
 *
 *		built from:	buildid.ifc
 */

#ifndef dds_c_buildid_h
#define dds_c_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "NDDSC_VERSION_5.2.3.0_BUILD_2016-04-25T07:37:01-07:00_RTI_RELEASE"
#endif

#endif /* dds_c_buildid_h */
